name: ETL • teina230

on:
  workflow_dispatch:
  schedule:
    - cron: "7 4 * * *"   # optioneel: dagelijks 04:07 UTC

jobs:
  etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run ETL (teina230)
        run: |
          set -euxo pipefail
          python etl/teina230.py
          ls -R data

      - name: Commit & push data changes
        run: |
          set -euxo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A data/
          git commit -m "chore(data): refresh TEINA230 • $(date -u +%Y-%m-%dT%H:%M:%SZ)" || echo "No changes"
          git pull --rebase
          git push
