name: ETL (minimal)

on:
  workflow_dispatch:      # handmatig starten
  schedule:
    - cron: "0 4 * * *"   # dagelijks 04:00 UTC

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show repo tree (debug)
        run: |
          pwd
          ls -la
          echo "---"
          ls -la etl || true

      - name: Set up Python 3.12 (no caching)
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run ETL script
        run: python etl/hello_etl.py

      - name: List generated files
        run: |
          echo "Generated files:"
          ls -la data/latest

      - name: Upload artifact (for download)
        uses: actions/upload-artifact@v4
        with:
          name: data-output
          path: data/latest/hello.json
