name: ETL and (optionally) publish

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: |
            etl/requirements.txt
            etl/pyproject.toml

      - name: Install deps (if present)
        run: |
          python -m pip install --upgrade pip
          if [ -f etl/requirements.txt ]; then pip install -r etl/requirements.txt; fi
          if [ -f etl/pyproject.toml ]; then pip install .; fi

      - name: Run ETL
        run: python etl/hello_etl.py
