name: ETL and publish data

on:
  workflow_dispatch:
  schedule:
    # Dagelijks 06:00 NL-tijd (≈ 04:00 UTC in zomer; 05:00 in winter)
    - cron: "0 4 * * *"

permissions:
  contents: write  # <- nodig om te kunnen pushen

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # nodig voor nette commits/pushes

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run ETL (Eurostat TEINA230)
        run: python etl/eurostat_teina230.py

      # Optioneel: bekijk even wat er veranderd is
      - name: Show git status
        run: |
          git status
          git diff --stat || true

      - name: Commit generated data (if changed)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Voeg alleen de data-map toe
          git add -A data/

          # Commit alleen als er staged changes zijn
          if git diff --cached --quiet; then
            echo "No data changes to commit."
            exit 0
          fi

          git commit -m "chore(data): update Eurostat TEINA230 outputs"
          git push

      # Altijd handig: upload ook als artifact om direct te downloaden
      - name: Upload data artifacts
        uses: actions/upload-artifact@v4
        with:
          name: eurostat-teina230-data
          path: |
            data/latest/eu_debt.json
            data/latest/manifest.json
            data/timeseries/eu_debt_12q.json
            data/snapshots/**/eu_debt.json
