name: ETL and (optionally) publish

on:
  schedule:
    - cron: "0 4 * * *"     # Dagelijks 04:00 UTC (= 06:00 NL zomertijd / 05:00 wintertijd)
  workflow_dispatch:        # Handmatig starten via de UI

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install deps (optional)
        run: |
          if [ -f etl/requirements.txt ]; then pip install -r etl/requirements.txt; fi

      - name: Run ETL
        run: python etl/hello_etl.py

      # --- Publiceren naar object storage (S3/R2) - optioneel, zie stap 2 ---
      # - name: Publish to object storage
      #   run: |
      #     aws s3 sync data/ s3://eufacts-data/ \
      #       --endpoint-url "${{ secrets.OBJ_ENDPOINT }}" \
      #       --acl public-read
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.OBJ_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.OBJ_SECRET }}

      - name: Store build artifact (voor test)
        uses: actions/upload-artifact@v4
        with:
          name: data-output
          path: data/latest/hello.json
