name: ETL (Eurostat TEINA230)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show repo tree (debug)
        run: |
          pwd
          ls -la
          echo "---"
          ls -la etl || true

      - name: Set up Python 3.12 (no caching)
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          if [ -f etl/requirements.txt ]; then pip install -r etl/requirements.txt; fi

      - name: Run Eurostat TEINA230 ETL
        run: python etl/teina230.py

      - name: List generated files
        run: |
          echo "Generated files under data/:"
          find data -type f -maxdepth 3 -print

      - name: Upload artifact (for download)
        uses: actions/upload-artifact@v4
        with:
          name: teina230-output
          path: |
            data/latest/eu_debt.json
            data/latest/manifest.json
            
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: eurostat-data
          path: data/
